### PR TITLE
Floor percentages

### PR DESCRIPTION
**Pull request by antonagestam**
Changes to round percentages down so that `99.99 ≠ 100`.

### CODE REVIEW

**Review by hannseman — APPROVED** [review]
Super!

**Comment by hannseman** [comment]
@antonagestam could you run `npm run package` in this PR?

**Comment by antonagestam** [comment]
@hannseman I finally got around to compiling :)

**Comment by antonagestam** [comment]
Hmm, but this failed: https://github.com/5monkeys/cobertura-action/runs/2803370740?check_suite_focus=true

**Comment by hannseman** [comment]
@antonagestam looks like something went wrong with the packaging, 16k deletions in dist/index.js. I get this output when building this PR:
```
$ npm run package

> cobertura-action@1.0.0 package
> ncc build index.js

ncc: Version 0.22.3
ncc: Compiling file index.js
478kB  dist/index.js
478kB  [1201ms] - ncc 0.22.3
```

Can you try removing `node_modules` and run `npm ci` first?

**Pull request merged**
