### PR TITLE
New input to hide coverage in collapsible <details>

### PR DESCRIPTION
**Pull request by sergekukharev**
I added a new option, `collapse_coverage`, that will allow hiding long file lists in the `<details>` tag.

GitHub [supports](https://github.github.com/gfm/#html-blocks) it as one of their HTML blocks:
<details>
<summary>I'm a spoiler!</summary>
Hello, world.
</details>

This change should be BC-compatible. It addresses some problems others tried to address in #49 and #65.

### CODE REVIEW

**Comment by sergekukharev** [comment]
I wonder if someone is still maintaining this Action. If not, are there any alternatives?

**Comment by felipetio** [comment]
@sergekukharev tks this is exactly what we need! Hopefully, this will be merged soon.

**Comment by W0nderMuffin** [comment]
is this still up-to-date?

**Comment by sergekukharev** [comment]
Closing this PR due to inactivity of the maintainers

**Pull request closed without merging**
