### PR TITLE
Add node 16 support for action

### PR DESCRIPTION
**Pull request by zymotik**
Fixes https://github.com/5monkeys/cobertura-action/issues/75

### CODE REVIEW

**Comment by zymotik** [comment]
Tested and working in forked repo PR https://github.com/zymotik/cobertura-action/pull/1

**Review by kodejack — APPROVED** [review]
Looks good to me

**Comment by zymotik** [comment]
@flaeppe @antonagestam @hannseman can any of you help to get this moving please?

**Review by flaeppe — APPROVED** [review]
Sorry for late response. Thanks for this!

**Comment by zhibek** [comment]
Hi @flaeppe @kodejack. Are there any plans to release a new version (v14?) of this, containing the changes merged with this PR? Doing so would resolve issue #84.

**Pull request merged**
